// Techniques available to ALL contexts regardless of direction
export const SHARED_TECHNIQUES = [
  'urge-surfing',
  'stop-skill',
  'accepts',
  'self-soothing',
  'breathing-478',
  'body-scan',
  'grounding-54321',
  'compassion-break',
  'values-compass',
  'defusion',
  'wise-mind',
  'cope-ahead',
  'radical-acceptance',
  'three-good-things',
  'decisional-balance',
  'problem-solving',
  'reframing',
  'gratitude-visit',
] as const;
