// Techniques available to ALL contexts regardless of direction
export const SHARED_TECHNIQUES = [
  'urge-surfing',
  'stop-skill',
  'accepts',
  'self-soothing',
  'breathing-478',
  'body-scan',
  'grounding-54321',
  'compassion-break',
  'values-compass',
  'defusion',
  'wise-mind',
  'cope-ahead',
  'radical-acceptance',
  'three-good-things',
  'decisional-balance',
  'problem-solving',
  'reframing',
  'gratitude-visit',
  'emotional-granularity',
  'coping-anchor',
  'somatic-reset',
  'nvc',
  'assertion-training',
  'boundary-message',
  'active-listening',
  'repair-talk',
  'sensory-refuge',
  'social-script',
] as const;
