import { defineContext } from '../lib/context';
import { substanceBase } from './_substance';

export default defineContext({
  ...substanceBase,
  id: 'alcohol',
  icon: '🍺',
  sortOrder: 25,
  showCrisis: true,
  applicableTechniques: [
    'urge-surfing',
    'stop-skill',
    'accepts',
    'self-soothing',
    'breathing-478',
    'body-scan',
    'grounding-54321',
    'compassion-break',
    'values-compass',
    'defusion',
    'wise-mind',
    'cope-ahead',
    'radical-acceptance',
    'three-good-things',
    'decisional-balance',
    'problem-solving',
    'reframing',
    'gratitude-visit',
    'emotional-granularity',
    'coping-anchor',
    'somatic-reset',
    'nvc',
    'assertion-training',
    'boundary-message',
    'active-listening',
    'repair-talk',
    'sensory-refuge',
    'social-script',
    'assertive-refusal',
    'time-out-request',
    'recovery-disclosure',
    'gradual-sharing',
    'concrete-request',
    'emotion-signal',
    'i-message',
    'appreciation-express',
    'reflective-question',
    'online-boundary',
    'anger-iceberg',
    'cognitive-reappraisal',
    'pause-before-react',
    'worry-time',
    'worry-tree',
    'good-enough',
    'energy-audit',
    'rest-types',
    'strengths-inventory',
    'connection-plan',
    'self-focus',
    'detachment',
    'exposure-ladder',
    'inner-critic',
    'shame-resilience',
    'work-detach',
    'needs-inventory',
    'community-find',
    'self-distancing',
    'rumination-interrupt',
    'rain-meditation',
    'three-minute-breathing',
    'savoring',
    'woop',
    'core-beliefs',
    'exception-finding',
    'act-matrix',
    'tipp',
    'halt-check',
    'urge-delay',
    'stimulus-control',
    'please-check',
    'opposite-action',
    'pros-cons-urge',
    'ask-support',
    'behavioral-substitution',
    'chain-break',
    'behavioral-chain',
    'emotion-check-in',
    'lapse-plan',
    'wrap-plan',
  ],
  i18n: {
    ja: {
      label: 'アルコール',
      description: '飲酒・お酒との付き合い方',
      impulse: '飲酒衝動',
      behavior: '飲むこと',
      condition: 'アルコール依存症',
      situation: '帰宅後・ストレス時・飲み会の後',
      bodyEffect: '肝臓・睡眠・記憶への影響',
      alternative: '炭酸水・ノンアルコール飲料・入浴',
    },
  },
});
