import { defineContext } from '../lib/context';
import { mentalBase } from './_mental';

export default defineContext({
  ...mentalBase,
  id: 'anger',
  icon: '😤',
  sortOrder: 2,
  applicableTechniques: [
    'pause-before-react',
    'anger-iceberg',
    'tipp',
    'stop-skill',
    'time-out-request',
    'emotion-labeling',
    'check-the-facts',
    'cognitive-reappraisal',
    'box-breathing',
    'somatic-reset',
    'resentment-release',
    'wise-mind',
    'i-message',
    'nvc',
    'radical-acceptance',
    'rumination-interrupt',
    'needs-inventory',
    'emotional-granularity',
    'self-compassion-3steps',
    'values-compass',
    'opposite-action',
    'assertion-training',
    'reframing',
    'decatastrophize',
    'progressive-relaxation',
    'grounding-54321',
    'body-scan',
    'life-position',
  ],
  i18n: {
    ja: {
      label: 'イライラが止まらない',
      description: '怒りの衝動・慢性的な恨みをコントロールする',
      impulse: '怒りの衝動・カッとなる感覚',
      behavior: '怒りを爆発させること',
      condition: '怒り・攻撃的な反応',
      situation: '批判された・不公平を感じた・裏切られたとき',
      goal: '怒りに飲み込まれずに、落ち着いて対応できること',
      obstacle: '反射的な言動・正当化・慢性的な恨み',
      trigger: '批判・期待外れ・不公平・無視されること',
      reward: '後悔のない言動・落ち着いた関係・自分への信頼',
      bodyEffect: '血圧上昇・心拍数増加・慢性的な緊張・免疫機能への影響',    },
  },
});
