import { defineContext } from '../lib/context';
import { substanceBase } from './_substance';

export default defineContext({
  ...substanceBase,
  id: 'caffeine',
  icon: '☕',
  sortOrder: 23,
  applicableTechniques: [
    'urge-surfing',
    'stop-skill',
    'accepts',
    'self-soothing',
    'breathing-478',
    'body-scan',
    'grounding-54321',
    'compassion-break',
    'values-compass',
    'defusion',
    'wise-mind',
    'cope-ahead',
    'radical-acceptance',
    'three-good-things',
    'decisional-balance',
    'problem-solving',
    'reframing',
    'gratitude-visit',
    'emotional-granularity',
    'coping-anchor',
    'somatic-reset',
    'nvc',
    'assertion-training',
    'boundary-message',
    'active-listening',
    'repair-talk',
    'sensory-refuge',
    'social-script',
    'assertive-refusal',
    'time-out-request',
    'recovery-disclosure',
    'gradual-sharing',
    'concrete-request',
    'emotion-signal',
    'i-message',
    'appreciation-express',
    'reflective-question',
    'online-boundary',
    'anger-iceberg',
    'cognitive-reappraisal',
    'pause-before-react',
    'worry-time',
    'worry-tree',
    'good-enough',
    'energy-audit',
    'rest-types',
    'strengths-inventory',
    'connection-plan',
    'self-focus',
    'detachment',
    'exposure-ladder',
    'inner-critic',
    'shame-resilience',
    'needs-inventory',
    'community-find',
    'self-distancing',
    'rumination-interrupt',
    'rain-meditation',
    'three-minute-breathing',
    'savoring',
    'woop',
    'core-beliefs',
    'exception-finding',
    'act-matrix',
    'tipp',
    'halt-check',
    'urge-delay',
    'stimulus-control',
    'please-check',
    'opposite-action',
    'pros-cons-urge',
    'ask-support',
    'behavioral-substitution',
    'chain-break',
    'trigger-list',
    'trigger-review',
    'self-monitoring',
    'behavioral-chain',
    'sleep-hygiene',
    'wait-10-min',
    'lapse-plan',
  ],
  i18n: {
    ja: {
      label: 'カフェイン',
      description: 'コーヒー・エナジードリンクの過剰摂取',
      impulse: 'カフェインへの渇望',
      behavior: 'コーヒーやエナジードリンクを飲むこと',
      condition: 'カフェイン依存',
      situation: '眠いとき・集中したいとき・習慣的に手が伸びるとき',
      bodyEffect: '睡眠・心拍・不安感への影響',
      alternative: 'ハーブティー・水・短い仮眠・軽いストレッチ',
    },
  },
});
