import { defineContext } from '../lib/context';
import { approachBase } from './_approach';

export default defineContext({
  ...approachBase,
  id: 'creativity',
  icon: '🎨',
  sortOrder: 18,
  applicableTechniques: [
    'question-storming',
    'reverse-brainstorm',
    'random-word',
    'freewriting',
    'quantity-first',
    'bad-art-day',
    'good-enough',
    'decatastrophize',
    'shame-resilience',
    'exposure-ladder',
    'best-friend-test',
    'gradual-sharing',
    'inner-critic',
    'defusion',
    'self-compassion-3steps',
    'self-distancing',
    'flow-activity',
    'creative-input',
    'savoring',
    'tiny-habits',
    'habit-stacking',
    'implementation-intention',
    'identity-statement',
    'environment-design',
    'temptation-bundling',
    'growth-mindset',
    'values-compass',
    'meaning-work',
    'strengths-use',
    'strengths-inventory',
    'best-possible-self',
    'behavioral-activation',
    'fresh-start',
    'rest-types',
    'motivation-source',
    'emotion-diary',
    'emotion-labeling',
    'thought-record',
    'cognitive-distortions',
    'trigger-review',
    'immunity-to-change',
  ],
  i18n: {
    ja: {
      label: '創作・趣味を楽しみたい',
      description: '絵・文章・音楽・工作など、創造的な活動を始めて続ける',
      impulse: '創りたい・表現したい気持ち',
      behavior: '創造的な活動をすること',
      condition: '創造性・趣味の継続',
      situation: 'やりたいのに手がつかないとき・完璧主義で動けないとき・インスピレーションが枯れているとき',
      bodyEffect: '創造的ブロックによる気分低下・無力感・意欲の喪失',      goal: '判断なしに創造を楽しめること',
      obstacle: '完璧主義・内なる批評家・インプット不足・時間がない',
      trigger: '「うまくできないかも」と思ったとき・白紙のページを前にしたとき',
      reward: 'フロー体験・自己表現の喜び・「続けている自分」への信頼感',
      alternative: '別のクリエイティブな活動・散歩・読書・インプット',    },
  },
});
