import { defineContext } from '../lib/context';
import { approachBase } from './_approach';

export default defineContext({
  ...approachBase,
  id: 'diet',
  icon: '🥗',
  sortOrder: 15,
  applicableTechniques: [
    'tiny-habits',
    'implementation-intention',
    'habit-stacking',
    'two-minute-rule',
    'if-then-planning',
    'environment-design',
    'behavioral-activation',
    'temptation-bundling',
    'self-monitoring',
    'opposite-action',
    'please-check',
    'ask-support',
    'cope-ahead',
    'reinforcement-management',
    'strengths-use',
    'best-possible-self',
    'fresh-start',
    'identity-statement',
    'motivation-source',
    'urge-surfing',
    'stop-skill',
    'accepts',
    'self-soothing',
    'breathing-478',
    'body-scan',
    'grounding-54321',
    'compassion-break',
    'values-compass',
    'defusion',
    'wise-mind',
    'cope-ahead',
    'radical-acceptance',
    'three-good-things',
    'decisional-balance',
    'problem-solving',
    'reframing',
    'gratitude-visit',
    'emotional-granularity',
    'coping-anchor',
    'somatic-reset',
    'nvc',
    'assertion-training',
    'boundary-message',
    'active-listening',
    'sensory-refuge',
    'social-script',
    'assertive-refusal',
    'time-out-request',
    'gradual-sharing',
    'concrete-request',
    'emotion-signal',
    'i-message',
    'appreciation-express',
    'reflective-question',
    'online-boundary',
    'anger-iceberg',
    'cognitive-reappraisal',
    'pause-before-react',
    'worry-time',
    'worry-tree',
    'good-enough',
    'energy-audit',
    'rest-types',
    'strengths-inventory',
    'connection-plan',
    'exposure-ladder',
    'inner-critic',
    'shame-resilience',
    'work-detach',
    'needs-inventory',
    'community-find',
    'self-distancing',
    'rumination-interrupt',
    'rain-meditation',
    'three-minute-breathing',
    'savoring',
    'woop',
    'core-beliefs',
    'exception-finding',
    'act-matrix',
    'mindful-eating',
    'hunger-scale',
    'food-freedom',
    'emotion-labeling',
    'emotion-diary',
    'behavioral-chain',
    'emotion-check-in',
    'body-image-diary',
    'halt-check',
  ],
  i18n: {
    ja: {
      label: '食生活を整えたい',
      description: '健康的な食習慣・ダイエット',
      impulse: '食事を整えたい気持ち',
      behavior: 'バランスよく食べること',
      condition: '食習慣の乱れ',
      situation: '外食が続いているとき・間食が止まらないとき',
      goal: '野菜を毎食食べること・間食を減らすこと',
      obstacle: '忙しさ・食欲・外食の誘い',
      trigger: '食事の準備をするとき・お腹が空いてきたとき',
      reward: '体の軽さ・肌の変化・エネルギーの安定',
      alternative: '水を飲む・散歩・野菜を先に食べる・別の食択',
      bodyEffect: '栄養バランスの乱れ・体重変動・消化器への影響・エネルギー代謝への影響',    },
  },
});
