import { defineContext } from '../lib/context';
import { substanceBase } from './_substance';

export default defineContext({
  ...substanceBase,
  id: 'drugs',
  icon: '💊',
  sortOrder: 27,
  showCrisis: true,
  applicableTechniques: [
    'urge-surfing',
    'stop-skill',
    'accepts',
    'self-soothing',
    'breathing-478',
    'body-scan',
    'grounding-54321',
    'compassion-break',
    'values-compass',
    'defusion',
    'wise-mind',
    'cope-ahead',
    'radical-acceptance',
    'three-good-things',
    'decisional-balance',
    'problem-solving',
    'reframing',
    'gratitude-visit',
    'emotional-granularity',
    'coping-anchor',
    'somatic-reset',
    'nvc',
    'assertion-training',
    'boundary-message',
    'active-listening',
    'repair-talk',
    'sensory-refuge',
    'social-script',
    'assertive-refusal',
    'time-out-request',
    'recovery-disclosure',
    'gradual-sharing',
    'concrete-request',
    'emotion-signal',
    'i-message',
    'appreciation-express',
    'reflective-question',
    'online-boundary',
    'anger-iceberg',
    'cognitive-reappraisal',
    'pause-before-react',
    'worry-time',
    'worry-tree',
    'good-enough',
    'energy-audit',
    'rest-types',
    'strengths-inventory',
    'connection-plan',
    'self-focus',
    'detachment',
    'exposure-ladder',
    'inner-critic',
    'shame-resilience',
    'work-detach',
    'needs-inventory',
    'community-find',
    'self-distancing',
    'rumination-interrupt',
    'rain-meditation',
    'three-minute-breathing',
    'savoring',
    'woop',
    'core-beliefs',
    'exception-finding',
    'act-matrix',
    'tipp',
    'halt-check',
    'urge-delay',
    'stimulus-control',
    'please-check',
    'opposite-action',
    'pros-cons-urge',
    'ask-support',
    'behavioral-substitution',
    'chain-break',
    'harm-reduction',
    'behavioral-chain',
    'emotion-check-in',
    'lapse-plan',
  ],
  i18n: {
    ja: {
      label: '薬物・市販薬',
      description: '違法薬物・市販薬の乱用・過剰服薬',
      impulse: '薬物への渇望',
      behavior: '使用すること',
      condition: '薬物依存症',
      situation: 'ストレス時・痛みを感じた時・孤独な夜',
      bodyEffect: '脳・臓器・依存耐性への影響',
      alternative: '専門家への連絡・散歩・冷水・信頼できる人に話す',
    },
  },
});
