import { defineContext } from '../lib/context';
import { behavioralBase, BEHAVIORAL_TECHNIQUES } from './_behavioral';

export default defineContext({
  ...behavioralBase,
  id: 'eating',
  icon: '🍽️',
  sortOrder: 20,
  applicableTechniques: [
    'halt-check',
    'urge-delay',
    'stimulus-control',
    'tipp',
    'behavioral-chain',
    'pros-cons-urge',
    'behavioral-substitution',
    'chain-break',
    'emotion-check-in',
    'please-check',
    'ask-support',
    'opposite-action',
    'urge-surfing',
    'stop-skill',
    'accepts',
    'self-soothing',
    'breathing-478',
    'body-scan',
    'grounding-54321',
    'compassion-break',
    'values-compass',
    'defusion',
    'wise-mind',
    'cope-ahead',
    'radical-acceptance',
    'three-good-things',
    'decisional-balance',
    'problem-solving',
    'reframing',
    'gratitude-visit',
    'emotional-granularity',
    'coping-anchor',
    'somatic-reset',
    'nvc',
    'assertion-training',
    'boundary-message',
    'active-listening',
    'repair-talk',
    'sensory-refuge',
    'social-script',
    'assertive-refusal',
    'time-out-request',
    'recovery-disclosure',
    'gradual-sharing',
    'concrete-request',
    'emotion-signal',
    'i-message',
    'appreciation-express',
    'reflective-question',
    'online-boundary',
    'anger-iceberg',
    'cognitive-reappraisal',
    'pause-before-react',
    'worry-time',
    'worry-tree',
    'good-enough',
    'energy-audit',
    'rest-types',
    'strengths-inventory',
    'connection-plan',
    'self-focus',
    'detachment',
    'exposure-ladder',
    'inner-critic',
    'shame-resilience',
    'needs-inventory',
    'community-find',
    'self-distancing',
    'rumination-interrupt',
    'rain-meditation',
    'three-minute-breathing',
    'savoring',
    'woop',
    'core-beliefs',
    'exception-finding',
    'act-matrix',
    'mindful-eating',
    'hunger-scale',
    'body-image-diary',
    'body-neutral',
    'food-freedom',
    'scale-detox',
    'trigger-list',
    'trigger-review',
    'self-monitoring',
    'lapse-plan',
    'wait-10-min',
    'harm-reduction',
  ],
  i18n: {
    ja: {
      label: '食べること（過食）',
      description: '過食・嘔吐・制限など摂食障害全般',
      impulse: '過食衝動',
      behavior: '食べること・嘔吐すること',
      condition: '摂食障害',
      situation: '食後や一人になった時',
      bodyEffect: '消化器系・電解質バランスへの影響',
      alternative: '散歩・日記・冷水・セルフソージング',
    },
  },
});
