import { defineContext } from '../lib/context';
import { mentalBase } from './_mental';
import { BEHAVIORAL_TECHNIQUES } from './_behavioral';

const PRIORITY = [
  'anger-iceberg', 'pause-before-react', 'cognitive-reappraisal',
  'stop-skill', 'tipp', 'emotion-labeling', 'check-the-facts', 'box-breathing',
] as const;

export default defineContext({
  ...mentalBase,
  id: 'emotional-reactivity',
  icon: '🌡️',
  sortOrder: 8,
  applicableTechniques: [
    'anger-iceberg',
    'pause-before-react',
    'cognitive-reappraisal',
    'stop-skill',
    'tipp',
    'emotion-labeling',
    'check-the-facts',
    'box-breathing',
    'halt-check',
    'urge-delay',
    'stimulus-control',
    'behavioral-chain',
    'pros-cons-urge',
    'behavioral-substitution',
    'chain-break',
    'emotion-check-in',
    'please-check',
    'ask-support',
    'opposite-action',
    'urge-surfing',
    'accepts',
    'self-soothing',
    'breathing-478',
    'body-scan',
    'grounding-54321',
    'compassion-break',
    'values-compass',
    'defusion',
    'wise-mind',
    'cope-ahead',
    'radical-acceptance',
    'three-good-things',
    'decisional-balance',
    'problem-solving',
    'reframing',
    'gratitude-visit',
    'emotional-granularity',
    'coping-anchor',
    'somatic-reset',
    'nvc',
    'assertion-training',
    'boundary-message',
    'active-listening',
    'repair-talk',
    'sensory-refuge',
    'social-script',
    'assertive-refusal',
    'time-out-request',
    'gradual-sharing',
    'concrete-request',
    'emotion-signal',
    'i-message',
    'appreciation-express',
    'reflective-question',
    'worry-time',
    'worry-tree',
    'good-enough',
    'energy-audit',
    'rest-types',
    'strengths-inventory',
    'connection-plan',
    'self-focus',
    'detachment',
    'inner-critic',
    'shame-resilience',
    'needs-inventory',
    'self-distancing',
    'rumination-interrupt',
    'rain-meditation',
    'three-minute-breathing',
    'savoring',
    'core-beliefs',
    'exception-finding',
    'act-matrix',
    'life-position',
  ],
  i18n: {
    ja: {
      label: '感情が爆発してしまう',
      description: '感情的な反応をコントロールする',
      impulse: '感情的な反応衝動',
      behavior: '落ち着いて反応すること',
      condition: '感情的な反応の問題',
      situation: 'カッとなってしまうとき・後から後悔することを言ってしまうとき',
      goal: '感情的にならずに状況に対処すること',
      obstacle: '反射的な言動・感情の高ぶり',
      trigger: '批判されたとき・期待を裏切られたとき・不公平を感じたとき',
      reward: '落ち着いた対話・後悔のない言動・自己肯定感の向上',
      alternative: '深呼吸・その場を離れる・冷水を飲む・手を動かす',    },
  },
});
