import { defineContext } from '../lib/context';
import { approachBase } from './_approach';

export default defineContext({
  ...approachBase,
  id: 'exercise',
  icon: '🏃',
  sortOrder: 14,
  applicableTechniques: [
    'tiny-habits',
    'implementation-intention',
    'habit-stacking',
    'two-minute-rule',
    'if-then-planning',
    'environment-design',
    'behavioral-activation',
    'temptation-bundling',
    'self-monitoring',
    'opposite-action',
    'please-check',
    'ask-support',
    'cope-ahead',
    'reinforcement-management',
    'strengths-use',
    'best-possible-self',
    'fresh-start',
    'identity-statement',
    'motivation-source',
    'urge-surfing',
    'stop-skill',
    'accepts',
    'self-soothing',
    'breathing-478',
    'body-scan',
    'grounding-54321',
    'compassion-break',
    'values-compass',
    'defusion',
    'wise-mind',
    'cope-ahead',
    'radical-acceptance',
    'three-good-things',
    'decisional-balance',
    'problem-solving',
    'reframing',
    'gratitude-visit',
    'emotional-granularity',
    'coping-anchor',
    'somatic-reset',
    'nvc',
    'assertion-training',
    'boundary-message',
    'active-listening',
    'sensory-refuge',
    'social-script',
    'assertive-refusal',
    'time-out-request',
    'gradual-sharing',
    'concrete-request',
    'emotion-signal',
    'i-message',
    'appreciation-express',
    'reflective-question',
    'online-boundary',
    'anger-iceberg',
    'cognitive-reappraisal',
    'pause-before-react',
    'worry-time',
    'worry-tree',
    'good-enough',
    'energy-audit',
    'rest-types',
    'strengths-inventory',
    'connection-plan',
    'exposure-ladder',
    'inner-critic',
    'shame-resilience',
    'work-detach',
    'needs-inventory',
    'community-find',
    'self-distancing',
    'rumination-interrupt',
    'rain-meditation',
    'three-minute-breathing',
    'savoring',
    'woop',
    'core-beliefs',
    'exception-finding',
    'act-matrix',
    'morning-walk',
    'emotion-labeling',
    'emotion-diary',
    'emotion-check-in',
    'behavioral-chain',
    'halt-check',
  ],
  i18n: {
    ja: {
      label: '運動を続けたい',
      description: '運動習慣を作る・続ける',
      impulse: '体を動かしたい気持ち',
      behavior: '運動すること',
      condition: '運動継続の困難',
      situation: '疲れて帰ってきたとき・天気が悪いとき',
      goal: '週○回運動すること',
      obstacle: '疲れ・面倒くさい・時間がない',
      trigger: '着替えるだけ・玄関を出るだけ',
      reward: '達成感・エンドルフィン・体の変化',
      alternative: '短い散歩・ストレッチ・別の身体活動・エレベーターを使わない',    },
  },
});
