import { defineContext } from '../lib/context';
import { behavioralBase } from './_behavioral';

export default defineContext({
  ...behavioralBase,
  id: 'gambling',
  icon: '🎰',
  sortOrder: 26,
  showCrisis: true,
  applicableTechniques: [
    'halt-check',
    'urge-delay',
    'stimulus-control',
    'tipp',
    'behavioral-chain',
    'pros-cons-urge',
    'behavioral-substitution',
    'chain-break',
    'emotion-check-in',
    'please-check',
    'ask-support',
    'opposite-action',
    'urge-surfing',
    'stop-skill',
    'accepts',
    'self-soothing',
    'breathing-478',
    'body-scan',
    'grounding-54321',
    'compassion-break',
    'values-compass',
    'defusion',
    'wise-mind',
    'cope-ahead',
    'radical-acceptance',
    'three-good-things',
    'decisional-balance',
    'problem-solving',
    'reframing',
    'gratitude-visit',
    'emotional-granularity',
    'coping-anchor',
    'somatic-reset',
    'nvc',
    'assertion-training',
    'boundary-message',
    'active-listening',
    'repair-talk',
    'sensory-refuge',
    'social-script',
    'assertive-refusal',
    'time-out-request',
    'recovery-disclosure',
    'gradual-sharing',
    'concrete-request',
    'emotion-signal',
    'i-message',
    'appreciation-express',
    'reflective-question',
    'online-boundary',
    'anger-iceberg',
    'cognitive-reappraisal',
    'pause-before-react',
    'worry-time',
    'worry-tree',
    'good-enough',
    'energy-audit',
    'rest-types',
    'strengths-inventory',
    'connection-plan',
    'self-focus',
    'detachment',
    'exposure-ladder',
    'inner-critic',
    'shame-resilience',
    'work-detach',
    'needs-inventory',
    'community-find',
    'self-distancing',
    'rumination-interrupt',
    'rain-meditation',
    'three-minute-breathing',
    'savoring',
    'woop',
    'core-beliefs',
    'exception-finding',
    'act-matrix',
    'lapse-plan',
    'wrap-plan',
  ],
  i18n: {
    ja: {
      label: 'ギャンブル',
      description: 'パチンコ・競馬・オンラインカジノなど',
      impulse: 'ギャンブル衝動',
      behavior: 'ギャンブルをすること',
      condition: 'ギャンブル依存症',
      situation: '負けを取り戻したい時・暇な時・給料日後',
      bodyEffect: '財務・人間関係・精神健康への影響',
      alternative: '財布を持たずに外出・別の刺激を探す・支援電話に電話',
    },
  },
});
