import { defineContext } from '../lib/context';
import { approachBase } from './_approach';

export default defineContext({
  ...approachBase,
  id: 'meditation',
  icon: '🧘',
  sortOrder: 17,
  applicableTechniques: [
    'tiny-habits',
    'implementation-intention',
    'habit-stacking',
    'two-minute-rule',
    'if-then-planning',
    'environment-design',
    'behavioral-activation',
    'temptation-bundling',
    'self-monitoring',
    'opposite-action',
    'please-check',
    'ask-support',
    'cope-ahead',
    'reinforcement-management',
    'strengths-use',
    'best-possible-self',
    'fresh-start',
    'identity-statement',
    'motivation-source',
    'urge-surfing',
    'stop-skill',
    'accepts',
    'self-soothing',
    'breathing-478',
    'body-scan',
    'grounding-54321',
    'compassion-break',
    'values-compass',
    'defusion',
    'wise-mind',
    'cope-ahead',
    'radical-acceptance',
    'three-good-things',
    'decisional-balance',
    'problem-solving',
    'reframing',
    'gratitude-visit',
    'emotional-granularity',
    'coping-anchor',
    'somatic-reset',
    'nvc',
    'assertion-training',
    'boundary-message',
    'active-listening',
    'sensory-refuge',
    'social-script',
    'assertive-refusal',
    'time-out-request',
    'gradual-sharing',
    'concrete-request',
    'emotion-signal',
    'i-message',
    'appreciation-express',
    'reflective-question',
    'online-boundary',
    'anger-iceberg',
    'cognitive-reappraisal',
    'pause-before-react',
    'worry-time',
    'worry-tree',
    'good-enough',
    'energy-audit',
    'rest-types',
    'strengths-inventory',
    'connection-plan',
    'exposure-ladder',
    'inner-critic',
    'shame-resilience',
    'work-detach',
    'needs-inventory',
    'community-find',
    'self-distancing',
    'rumination-interrupt',
    'rain-meditation',
    'three-minute-breathing',
    'savoring',
    'woop',
    'core-beliefs',
    'exception-finding',
    'act-matrix',
    'walking-meditation',
    'leaves-on-stream',
    'loving-kindness',
    'box-breathing',
    'present-moment',
    'self-as-context',
  ],
  i18n: {
    ja: {
      label: 'ひと息ついて心を整えたい',
      description: '瞑想・マインドフルネスを日課にする',
      impulse: '静かに内省したい気持ち',
      behavior: '瞑想すること・呼吸に集中すること',
      condition: 'ストレスや不安',
      situation: 'バタバタした日・頭がうるさいとき',
      goal: '毎朝○分瞑想すること',
      obstacle: '雑念・時間がない・効果が感じられない',
      trigger: '起床直後・同じ場所・同じクッション',
      reward: '心の静けさ・感情の安定・集中力の向上',
      alternative: '深呼吸・軽い散歩・お茶を飲む・自然に触れる',    },
  },
});
