import { defineContext } from '../lib/context';
import { mentalBase } from './_mental';

export default defineContext({
  ...mentalBase,
  id: 'perfectionism',
  icon: '🎯',
  sortOrder: 7,
  applicableTechniques: [
    'good-enough',
    'inner-critic',
    'shame-resilience',
    'cognitive-reappraisal',
    'self-compassion-3steps',
    'defusion',
    'radical-acceptance',
    'reframing',
    'values-compass',
    'wise-mind',
    'decatastrophize',
    'letter-to-self',
    'loving-kindness',
    'kind-words',
    'growth-mindset',
    'three-good-things',
    'gratitude-visit',
    'problem-solving',
    'decisional-balance',
    'emotional-granularity',
    'pause-before-react',
    'breathing-478',
    'grounding-54321',
    'body-scan',
    'compassion-break',
    'behavioral-experiment',
    'immunity-to-change',
    'thought-record',
    'cognitive-distortions',
    'emotion-diary',
    'downward-arrow',
    'emotion-check-in',
  ],
  i18n: {
    ja: {
      label: '自分に厳しすぎてしまう',
      description: '「十分よい」を認められるようになる',
      impulse: '完璧にしなければという衝動',
      behavior: '完璧を手放して行動すること',
      condition: '完璧主義',
      situation: 'ミスが怖くて動けないとき・自分を責め続けているとき',
      goal: '「十分よい」で完了できるようになること',
      obstacle: '全か無か思考・自己批判・先延ばし',
      trigger: '評価される場面・失敗したとき・人と比較したとき',
      reward: '行動できる喜び・自己批判の減少・完了の達成感',
      bodyEffect: '慢性的なストレス・睡眠障害・燃え尽き・身体的緊張',    },
  },
});
