import { defineContext } from '../lib/context';
import { mentalBase } from './_mental';

export default defineContext({
  ...mentalBase,
  id: 'procrastination',
  icon: '⏳',
  sortOrder: 12,
  applicableTechniques: [
    'zeigarnik-start',
    'task-aversion-check',
    'pomodoro',
    'two-minute-rule',
    'opposite-action',
    'implementation-intention',
    'tiny-habits',
    'self-compassion-3steps',
    'behavioral-activation',
    'environment-design',
    'temptation-bundling',
    'values-compass',
    'decatastrophize',
    'woop',
    'cope-ahead',
    'commitment-action',
    'emotion-check-in',
    'cognitive-distortions',
    'problem-solving',
    'motivation-source',
    'identity-statement',
    'fresh-start',
    'todays-step',
    'reinforcement-management',
    'growth-mindset',
    'defusion',
    'wise-mind',
    'if-then-planning',
    'body-scan',
    'three-wins',
    'cognitive-reappraisal',
    'mit-selection',
    'immunity-to-change',
    'emotion-diary',
    'emotion-labeling',
    'thought-record',
    'behavioral-chain',
    'trigger-review',
    'downward-arrow',
    'fear-inventory',
  ],
  i18n: {
    ja: {
      label: 'やるべきことが進まない',
      description: '「あとでやろう」の衝動に気づき、今すぐ取り掛かる力を育てる',
      impulse: '「あとでやろう」という衝動',
      behavior: '先延ばしすること',
      condition: '先延ばし・回避',
      situation: 'タスクを前にして腰が重いとき・締め切りが近いのに動けないとき',
      goal: 'やるべきことにその日のうちに取り掛かること',
      obstacle: '完璧主義・失敗への恐れ・圧倒される感覚・やる気待ち',
      trigger: '「あとでやろう」と思った瞬間・タスクリストを見たとき',
      alternative: 'まず2分だけ取り掛かること',
      reward: '達成感・自分への信頼感・締め切り前の余裕',
      bodyEffect: '慢性的な罪悪感・集中力低下・締切ストレスによる身体症状',    },
  },
});
