import { defineContext } from '../lib/context';
import { approachBase } from './_approach';

export default defineContext({
  ...approachBase,
  id: 'productivity',
  icon: '⚡',
  sortOrder: 19,
  applicableTechniques: [
    'mit-selection',
    'task-batching',
    'weekly-review',
    'deep-work-block',
    'pomodoro',
    'environment-design',
    'stimulus-control',
    'zeigarnik-start',
    'two-minute-rule',
    'task-aversion-check',
    'implementation-intention',
    'if-then-planning',
    'shutdown-ritual',
    'work-detach',
    'energy-audit',
    'please-check',
    'question-storming',
    'reverse-brainstorm',
    'random-word',
    'tiny-habits',
    'habit-stacking',
    'identity-statement',
    'motivation-source',
    'self-monitoring',
    'todays-step',
    'reinforcement-management',
    'problem-solving',
    'growth-mindset',
    'values-compass',
    'eisenhower-matrix',
    'time-blocking',
    'time-audit',
    'parkinson-defense',
    'ideal-week-design',
    'emotion-diary',
    'emotion-check-in',
    'thought-record',
    'downward-arrow',
    'behavioral-chain',
    'trigger-review',
  ],
  i18n: {
    ja: {
      label: '仕事をうまく回したい',
      description: '集中・優先順位・時間管理で仕事の生産性を上げる',
      impulse: '仕事をうまくこなしたい気持ち',
      behavior: '仕事を効率よく進めること',
      condition: '仕事の生産性・効率',
      situation: 'やることが多すぎるとき・集中できないとき・仕事が終わらないとき',
      goal: '大切な仕事を、決まった時間内に終わらせること',
      obstacle: '割り込み・先延ばし・優先順位の混乱・エネルギー不足',
      trigger: '「何から手をつければいいか分からない」と感じたとき',
      reward: '定時に終わる達成感・「大切な仕事が進んだ」という満足感',
      alternative: '優先タスクの整理・小さな一歩・休憩・別の仕事',    },
  },
});
