import { defineContext } from '../lib/context';
import { mentalBase } from './_mental';

export default defineContext({
  ...mentalBase,
  id: 'rumination',
  icon: '🌀',
  sortOrder: 6,
  applicableTechniques: [
    'self-distancing',
    'rumination-interrupt',
    'defusion',
    'leaves-on-stream',
    'worry-time',
    'grounding-54321',
    'radical-acceptance',
    'self-compassion-3steps',
    'inner-critic',
    'cognitive-reappraisal',
    'present-moment',
    'body-scan',
    'loving-kindness',
    'breathing-478',
    'box-breathing',
    'stop-skill',
    'emotional-granularity',
    'somatic-reset',
    'coping-anchor',
    'compassion-break',
    'wise-mind',
    'acceptance',
    'reframing',
    'letter-to-self',
    'kind-words',
    'three-good-things',
    'pause-before-react',
  ],
  i18n: {
    ja: {
      label: '同じことをぐるぐる考えてしまう',
      description: '不快な記憶や考えが繰り返し浮かぶのをやわらげる',
      impulse: '嫌な記憶や考えが繰り返し浮かぶ',
      behavior: '思考に飲み込まれず、今に戻ること',
      condition: '反芻思考・侵入思考',
      situation: '嫌な記憶が頭から離れないとき・同じ後悔を何度も思い出すとき',
      goal: '思考を観察し、流せるようになること',
      obstacle: '思考の連鎖・自動的な反芻・感情への飲み込まれ',
      trigger: 'ふとした瞬間・夜一人でいるとき・関連する話題を聞いたとき',
      reward: '思考からの解放感・今この瞬間への集中・心の静けさ',
      bodyEffect: '睡眠障害・慢性的な精神疲労・抑うつ傾向・集中力低下',    },
  },
});
