import { defineContext } from '../lib/context';
import { behavioralBase } from './_behavioral';

// スコープ：自慰行為・軽度の性的衝動（性的暴力等は対象外）
export default defineContext({
  ...behavioralBase,
  id: 'sexual',
  icon: '💙',
  sortOrder: 22,
  showCrisis: true,
  applicableTechniques: [
    'halt-check',
    'urge-delay',
    'stimulus-control',
    'tipp',
    'behavioral-chain',
    'pros-cons-urge',
    'behavioral-substitution',
    'chain-break',
    'emotion-check-in',
    'please-check',
    'ask-support',
    'opposite-action',
    'urge-surfing',
    'stop-skill',
    'accepts',
    'self-soothing',
    'breathing-478',
    'body-scan',
    'grounding-54321',
    'compassion-break',
    'values-compass',
    'defusion',
    'wise-mind',
    'cope-ahead',
    'radical-acceptance',
    'three-good-things',
    'decisional-balance',
    'problem-solving',
    'reframing',
    'gratitude-visit',
    'emotional-granularity',
    'coping-anchor',
    'somatic-reset',
    'nvc',
    'assertion-training',
    'boundary-message',
    'active-listening',
    'repair-talk',
    'sensory-refuge',
    'social-script',
    'assertive-refusal',
    'time-out-request',
    'recovery-disclosure',
    'gradual-sharing',
    'concrete-request',
    'emotion-signal',
    'i-message',
    'appreciation-express',
    'reflective-question',
    'online-boundary',
    'anger-iceberg',
    'cognitive-reappraisal',
    'pause-before-react',
    'worry-time',
    'worry-tree',
    'good-enough',
    'energy-audit',
    'rest-types',
    'strengths-inventory',
    'connection-plan',
    'self-focus',
    'detachment',
    'exposure-ladder',
    'inner-critic',
    'shame-resilience',
    'needs-inventory',
    'community-find',
    'self-distancing',
    'rumination-interrupt',
    'rain-meditation',
    'three-minute-breathing',
    'savoring',
    'woop',
    'core-beliefs',
    'exception-finding',
    'act-matrix',
    'trigger-list',
    'trigger-review',
    'self-monitoring',
    'lapse-plan',
    'wait-10-min',
  ],
  i18n: {
    ja: {
      label: '性的衝動',
      description: '自慰・軽度の性的衝動のコントロール',
      impulse: '性的衝動',
      behavior: '自慰・性的なコンテンツを見ること',
      condition: '性的強迫',
      situation: '夜・孤独を感じた時・退屈な時',
      bodyEffect: '睡眠・自己認識・関係性への影響',
      alternative: '運動・冷水シャワー・没頭できる活動',
    },
  },
});
