import { defineContext } from '../lib/context';
import { behavioralBase } from './_behavioral';

export default defineContext({
  ...behavioralBase,
  id: 'shopping',
  icon: '🛍️',
  sortOrder: 21,
  applicableTechniques: [
    'halt-check',
    'urge-delay',
    'stimulus-control',
    'tipp',
    'behavioral-chain',
    'pros-cons-urge',
    'behavioral-substitution',
    'chain-break',
    'emotion-check-in',
    'please-check',
    'ask-support',
    'opposite-action',
    'urge-surfing',
    'stop-skill',
    'accepts',
    'self-soothing',
    'breathing-478',
    'body-scan',
    'grounding-54321',
    'compassion-break',
    'values-compass',
    'defusion',
    'wise-mind',
    'cope-ahead',
    'radical-acceptance',
    'three-good-things',
    'decisional-balance',
    'problem-solving',
    'reframing',
    'gratitude-visit',
    'emotional-granularity',
    'coping-anchor',
    'somatic-reset',
    'nvc',
    'assertion-training',
    'boundary-message',
    'active-listening',
    'repair-talk',
    'sensory-refuge',
    'social-script',
    'assertive-refusal',
    'time-out-request',
    'recovery-disclosure',
    'gradual-sharing',
    'concrete-request',
    'emotion-signal',
    'i-message',
    'appreciation-express',
    'reflective-question',
    'online-boundary',
    'anger-iceberg',
    'cognitive-reappraisal',
    'pause-before-react',
    'worry-time',
    'worry-tree',
    'good-enough',
    'energy-audit',
    'rest-types',
    'strengths-inventory',
    'connection-plan',
    'self-focus',
    'detachment',
    'exposure-ladder',
    'inner-critic',
    'shame-resilience',
    'needs-inventory',
    'community-find',
    'self-distancing',
    'rumination-interrupt',
    'rain-meditation',
    'three-minute-breathing',
    'savoring',
    'woop',
    'core-beliefs',
    'exception-finding',
    'act-matrix',
    'trigger-list',
    'trigger-review',
    'self-monitoring',
    'lapse-plan',
    'enough-definition',
    'hedonic-treadmill',
    'loss-aversion-check',
    'wait-10-min',
  ],
  i18n: {
    ja: {
      label: '衝動買い・買い物',
      description: '衝動買い・買い物依存・オンライン購入',
      impulse: '買い物衝動',
      behavior: '買うこと・カートに入れること',
      condition: '買い物依存症',
      situation: 'ストレス後・セール時・暇な時',
      bodyEffect: '財務状況・自己嫌悪・片付けへの影響',
      alternative: '24時間待つ・ウィッシュリストに入れるだけ・別のことに集中',
    },
  },
});
