import { defineContext } from '../lib/context';
import { approachBase } from './_approach';

export default defineContext({
  ...approachBase,
  id: 'sleep',
  icon: '😴',
  sortOrder: 11,
  applicableTechniques: [
    'tiny-habits',
    'implementation-intention',
    'habit-stacking',
    'two-minute-rule',
    'if-then-planning',
    'environment-design',
    'behavioral-activation',
    'temptation-bundling',
    'self-monitoring',
    'opposite-action',
    'please-check',
    'ask-support',
    'cope-ahead',
    'reinforcement-management',
    'strengths-use',
    'best-possible-self',
    'fresh-start',
    'identity-statement',
    'motivation-source',
    'urge-surfing',
    'stop-skill',
    'accepts',
    'self-soothing',
    'breathing-478',
    'body-scan',
    'grounding-54321',
    'compassion-break',
    'values-compass',
    'defusion',
    'wise-mind',
    'cope-ahead',
    'radical-acceptance',
    'three-good-things',
    'decisional-balance',
    'problem-solving',
    'reframing',
    'gratitude-visit',
    'emotional-granularity',
    'coping-anchor',
    'somatic-reset',
    'nvc',
    'assertion-training',
    'boundary-message',
    'active-listening',
    'sensory-refuge',
    'social-script',
    'assertive-refusal',
    'time-out-request',
    'gradual-sharing',
    'concrete-request',
    'emotion-signal',
    'i-message',
    'appreciation-express',
    'reflective-question',
    'online-boundary',
    'anger-iceberg',
    'cognitive-reappraisal',
    'pause-before-react',
    'worry-time',
    'worry-tree',
    'good-enough',
    'energy-audit',
    'rest-types',
    'strengths-inventory',
    'connection-plan',
    'exposure-ladder',
    'inner-critic',
    'shame-resilience',
    'work-detach',
    'needs-inventory',
    'community-find',
    'self-distancing',
    'rumination-interrupt',
    'rain-meditation',
    'three-minute-breathing',
    'savoring',
    'woop',
    'core-beliefs',
    'exception-finding',
    'act-matrix',
    'sleep-hygiene',
    'sleep-routine',
    'digital-sunset',
    'progressive-relaxation',
    'box-breathing',
  ],
  i18n: {
    ja: {
      label: '眠れない夜がある',
      description: '睡眠の質・量を改善する',
      impulse: '早く寝たい気持ち',
      behavior: '決まった時間に眠ること',
      condition: '睡眠の問題',
      situation: '夜更かしが続いているとき・スマホが手放せないとき',
      goal: '毎日○時間眠ること',
      obstacle: '夜更かし・スマホ・眠れない不安',
      trigger: '就寝1時間前・アラームを設定したとき',
      reward: '朝の爽快感・集中力の向上',
      alternative: '読書・軽いストレッチ・瞑想・深呼吸・ハーブティー',    },
  },
});
