import { defineContext } from '../lib/context';
import { substanceBase } from './_substance';

export default defineContext({
  ...substanceBase,
  id: 'smoking',
  icon: '🚬',
  sortOrder: 24,
  showCrisis: true,
  applicableTechniques: [
    'urge-surfing',
    'stop-skill',
    'accepts',
    'self-soothing',
    'breathing-478',
    'body-scan',
    'grounding-54321',
    'compassion-break',
    'values-compass',
    'defusion',
    'wise-mind',
    'cope-ahead',
    'radical-acceptance',
    'three-good-things',
    'decisional-balance',
    'problem-solving',
    'reframing',
    'gratitude-visit',
    'emotional-granularity',
    'coping-anchor',
    'somatic-reset',
    'nvc',
    'assertion-training',
    'boundary-message',
    'active-listening',
    'repair-talk',
    'sensory-refuge',
    'social-script',
    'assertive-refusal',
    'time-out-request',
    'recovery-disclosure',
    'gradual-sharing',
    'concrete-request',
    'emotion-signal',
    'i-message',
    'appreciation-express',
    'reflective-question',
    'online-boundary',
    'anger-iceberg',
    'cognitive-reappraisal',
    'pause-before-react',
    'worry-time',
    'worry-tree',
    'good-enough',
    'energy-audit',
    'rest-types',
    'strengths-inventory',
    'connection-plan',
    'self-focus',
    'detachment',
    'exposure-ladder',
    'inner-critic',
    'shame-resilience',
    'needs-inventory',
    'community-find',
    'self-distancing',
    'rumination-interrupt',
    'rain-meditation',
    'three-minute-breathing',
    'savoring',
    'woop',
    'core-beliefs',
    'exception-finding',
    'act-matrix',
    'tipp',
    'halt-check',
    'urge-delay',
    'stimulus-control',
    'please-check',
    'opposite-action',
    'pros-cons-urge',
    'ask-support',
    'behavioral-substitution',
    'chain-break',
    'trigger-list',
    'trigger-review',
    'behavioral-chain',
    'self-monitoring',
    'sleep-hygiene',
    'physiological-sigh',
    'wait-10-min',
    'lapse-plan',
  ],
  i18n: {
    ja: {
      label: 'タバコ・ニコチン',
      description: '喫煙・ニコチン依存',
      impulse: '喫煙衝動',
      behavior: '吸うこと',
      condition: 'ニコチン依存症',
      situation: 'コーヒーの後・ストレス時・食後',
      bodyEffect: '肺・心臓・皮膚・ニコチン耐性への影響',
      alternative: 'ガム・深呼吸・水を飲む・手を動かす',
    },
  },
});
