import { defineContext } from '../lib/context';
import { mentalBase } from './_mental';

export default defineContext({
  ...mentalBase,
  id: 'social-anxiety',
  icon: '🫣',
  sortOrder: 5,
  applicableTechniques: [
    'exposure-ladder',
    'attention-redirect',
    'behavioral-experiment',
    'cognitive-distortions',
    'decatastrophize',
    'best-friend-test',
    'shame-resilience',
    'social-script',
    'cope-ahead',
    'box-breathing',
    'self-distancing',
    'inner-critic',
    'pie-chart',
    'gradual-sharing',
    'defusion',
    'acceptance',
    'check-the-facts',
    'cognitive-reappraisal',
    'self-compassion-3steps',
    'values-compass',
    'loving-kindness',
    'somatic-reset',
    'grounding-54321',
    'emotion-labeling',
    'worry-time',
    'body-scan',
    'breathing-478',
    'emotion-diary',
    'thought-record',
    'downward-arrow',
    'emotion-check-in',
    'behavioral-chain',
    'fear-inventory',
    'life-position',
  ],
  i18n: {
    ja: {
      label: '人付き合いがしんどい',
      description: '人前・社交場面での緊張・対人恐怖に向き合う',
      impulse: '人に評価される恐れ・恥をかく恐れ',
      behavior: '社交場面を避けること',
      condition: '社交不安・対人恐怖',
      situation: '人前で話すとき・初対面の相手と話すとき・グループの中にいるとき',
      goal: '不安があっても、大切な社交場面に踏み出せること',
      obstacle: '評価への恐れ・完璧主義・恥の感覚・回避',
      trigger: '注目を浴びるとき・自己紹介・プレゼン・食事会',
      alternative: '深呼吸・その場を離れる・信頼できる人に話す',      reward: 'つながりの感覚・自己効力感・避けなかった達成感',
      bodyEffect: '動悸・発汗・震え・回避行動による機会の喪失・疲弊感',    },
  },
});
