import { defineContext } from '../lib/context';
import { approachBase } from './_approach';

export default defineContext({
  ...approachBase,
  id: 'study',
  icon: '📚',
  sortOrder: 16,
  applicableTechniques: [
    'tiny-habits',
    'implementation-intention',
    'habit-stacking',
    'two-minute-rule',
    'if-then-planning',
    'environment-design',
    'behavioral-activation',
    'temptation-bundling',
    'self-monitoring',
    'opposite-action',
    'please-check',
    'ask-support',
    'cope-ahead',
    'reinforcement-management',
    'strengths-use',
    'best-possible-self',
    'fresh-start',
    'identity-statement',
    'motivation-source',
    'urge-surfing',
    'stop-skill',
    'accepts',
    'self-soothing',
    'breathing-478',
    'body-scan',
    'grounding-54321',
    'compassion-break',
    'values-compass',
    'defusion',
    'wise-mind',
    'cope-ahead',
    'radical-acceptance',
    'three-good-things',
    'decisional-balance',
    'problem-solving',
    'reframing',
    'gratitude-visit',
    'emotional-granularity',
    'coping-anchor',
    'somatic-reset',
    'nvc',
    'assertion-training',
    'boundary-message',
    'active-listening',
    'sensory-refuge',
    'social-script',
    'assertive-refusal',
    'time-out-request',
    'gradual-sharing',
    'concrete-request',
    'emotion-signal',
    'i-message',
    'appreciation-express',
    'reflective-question',
    'online-boundary',
    'anger-iceberg',
    'cognitive-reappraisal',
    'pause-before-react',
    'worry-time',
    'worry-tree',
    'good-enough',
    'energy-audit',
    'rest-types',
    'strengths-inventory',
    'connection-plan',
    'exposure-ladder',
    'inner-critic',
    'shame-resilience',
    'work-detach',
    'needs-inventory',
    'community-find',
    'self-distancing',
    'rumination-interrupt',
    'rain-meditation',
    'three-minute-breathing',
    'savoring',
    'woop',
    'core-beliefs',
    'exception-finding',
    'act-matrix',
    'pomodoro',
    'zeigarnik-start',
    'task-aversion-check',
  ],
  i18n: {
    ja: {
      label: '勉強を続けたい',
      description: '学習習慣・読書・資格取得',
      impulse: '学びたい気持ち',
      behavior: '勉強すること・本を読むこと',
      condition: '学習継続の困難',
      situation: 'やる気が出ないとき・集中できないとき',
      goal: '毎日○分勉強すること',
      obstacle: 'やる気・集中力・スマホの誘惑',
      trigger: '同じ場所・同じ時間・テキストを開くだけ',
      reward: '達成感・知識の蓄積・将来の選択肢',
      alternative: '短い休憩・別の科目・ポモドーロ・環境を変える',    },
  },
});
